@startuml

title FrameI_ControlByte

participant Driver
participant Device

Driver -> Device : 10 (‭0001 0000‬)
Device -> Driver : 30 (‭0011 0000‬)
......
Driver -> Device : 32 (‭0011 0010‬)
Device -> Driver : 52 (‭0101 0010‬)
......
Driver -> Device : 54 (‭0101 0100‬)
Device -> Driver : 74 (‭0111 0100‬)
......
Driver -> Device : 76 (‭0111 0110‬)
Device -> Driver : 96 (‭1001 0110‬)
......
Driver -> Device : 98 (‭1001 1000‬)
Device -> Driver : B8 (‭1011 1000‬)
......
Driver -> Device : BA (‭1011 1010‬)
Device -> Driver : DA (‭1101 1010‬)
......
Driver -> Device : DC (‭1101 1100‬)
Device -> Driver : FC (‭1111 1100‬)
......
Driver -> Device : FE (‭1111 1110‬)
Device -> Driver : 1E (‭0001 1110‬)

=== Without Hexes ===

Driver -> Device : ‭0001 0000
Driver <- Device : ‭0011 0000
......
Driver -> Device : ‭0011 0010
Driver <- Device : ‭0101 0010
......
Driver -> Device : ‭0101 0100
Driver <- Device : ‭0111 0100
......
Driver -> Device : ‭0111 0110
Device -> Driver : ‭1001 0110
......  
Driver -> Device : ‭1001 1000
Device -> Driver : ‭1011 1000
......
Driver -> Device : ‭1011 1010
Device -> Driver : ‭1101 1010
......
Driver -> Device : ‭1101 1100
Device -> Driver : ‭1111 1100
......
Driver -> Device : ‭1111 1110
Device -> Driver : ‭0001 1110

footer Pawel Korycinski
@enduml